[package]
name = "deno_mongo"
version = "0.1.0"
authors = ["Enok <416828041@qq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mongodb = { version = "0.9.2" }
bson = "0.14.1"
serde_json = "1.0.52"
serde = "1.0.106"
futures = "0.3.5"
deno_core = "0.45.0"
lazy_static = "1.4.0"
